### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by arrested-developer**
Sorry for dragging my feet on this - between new baby and trying to get some freelance work done I've had so little time.

This update adds some features and refactors the code to use promises more consistently, and for the code to be more self-documenting.

All configuration has been moved to environment variables to allow for changes to be made easily to e.g. CF name

It's my intention that this update makes the codebase easier to build upon, happy to explain anything that isn't clear already :smiley:

This adds some features, mainly that it's possible to send invitations and reminder invitations by simply checking a box in Airtable. The Tech for Better Leads airtable will need some fields adding as per [this example](https://airtable.com/shrPz9lEEo5PheVna) for the new features.

I've documented everything in the readme, please take a look there and ask away if anything isn't clear.

Thanks!

### CODE REVIEW

**Comment by charlielafosse** [comment]
Thanks so much for this @arrested-developer ! Will have a look over today :sunflower:

**Comment by charlielafosse** [comment]
And apologies - that conflict is my fault, as I just made a one-line edit straight to master, wanting to send out emails asap to POs. And didn't see this PR! :scream:

**Review by charlielafosse — CHANGES_REQUESTED** [review]
Looks great, having stuff in a config file is a good shout.

Could we change lines 20-21 of `sendFollowUpSurvey.js`: 

```
<p>When we have received your survey response, we will invite you to the next Definition
  workshop.</p>
```

Since we won't necessarily invite them straight away to a Definition Workshop after they've submitted their user research - maybe something along the lines of keeping them up to date with the selection process for their project?

**Comment by sofer** [comment]
@arrested-developer I don't pretend to have looked at every line, but I like the factoring out of all config into a single file and the separation of functions by interface in your model folder  👍

**Review by sofer — APPROVED** [review]

**Comment by charlielafosse** [comment]
Merged this cos it was a biggy, will make a separate small PR for the wording changes :shipit:

**Pull request merged**
